# Generated by Django 5.2.15 on 2026-06-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkpoints', '0001_initial'),
        ('rondas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('sesion', 'Sesión'), ('ronda', 'Ronda'), ('novedad', 'Novedad'), ('error', 'Error')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_evento',
            },
        ),
        migrations.CreateModel(
            name='LibroNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion_id', models.BigIntegerField()),
                ('guardia_keycloak_id', models.CharField(db_index=True, max_length=36)),
                ('dispositivo_id', models.BigIntegerField(blank=True, null=True)),
                ('timestamp_evento', models.DateTimeField()),
                ('timestamp_servidor', models.DateTimeField()),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('distancia_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('dentro_geocerca', models.BooleanField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('error', 'Error')], default='ok', max_length=10)),
                ('texto', models.TextField(blank=True, null=True)),
                ('punto_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checkpoints.puntocontrol')),
                ('ronda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rondas.ronda')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novedades.tipoevento')),
            ],
            options={
                'db_table': 'libro_novedades',
            },
        ),
        migrations.CreateModel(
            name='LibroNovedadesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('libro_novedades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios', to='novedades.libronovedades')),
            ],
            options={
                'db_table': 'libro_novedades_media',
            },
        ),
        migrations.AddIndex(
            model_name='libronovedades',
            index=models.Index(fields=['instalacion_id', 'timestamp_evento'], name='libro_noved_instala_752424_idx'),
        ),
    ]
