# Generated by Django 5.2.15 on 2026-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_seed_ronda_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libronovedades',
            name='comentario_central',
            field=models.TextField(blank=True, null=True),
        ),
    ]
