# Generated by Django 5.2.15 on 2026-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion_id', models.BigIntegerField(db_index=True)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('tolerancia_mts', models.SmallIntegerField(default=30)),
                ('validar_posicion', models.BooleanField(default=True)),
                ('foto_path', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_token', models.CharField(max_length=36, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'punto_control',
            },
        ),
    ]
