# Generated by Django 5.2.15 on 2026-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0002_tipo_codigo_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntocontrol',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
        migrations.AlterField(
            model_name='puntocontrol',
            name='lng',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
    ]
