# Generated by Django 5.2.15 on 2026-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0003_alter_puntocontrol_lat_alter_puntocontrol_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntocontrol',
            name='lat',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='puntocontrol',
            name='lng',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
