# Generated by Django 5.2.15 on 2026-06-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repite', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programacion',
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.BigIntegerField(db_index=True)),
                ('instalacion_id', models.BigIntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ronda',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.PositiveSmallIntegerField()),
                ('minuto', models.PositiveSmallIntegerField()),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rondas.programacion')),
            ],
            options={
                'db_table': 'programacion_horario',
            },
        ),
        migrations.AddField(
            model_name='programacion',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rondas.ronda'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino_tipo', models.CharField(choices=[('guardia', 'Guardia'), ('grupo', 'Grupo'), ('todos', 'Todos')], max_length=10)),
                ('destino_ref', models.CharField(blank=True, max_length=80, null=True)),
                ('anticipacion_min', models.SmallIntegerField()),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rondas.ronda')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='RondaGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardia_keycloak_id', models.CharField(db_index=True, max_length=36)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rondas.ronda')),
            ],
            options={
                'db_table': 'ronda_guardia',
                'constraints': [models.UniqueConstraint(fields=('ronda', 'guardia_keycloak_id'), name='uq_ronda_guardia')],
            },
        ),
        migrations.CreateModel(
            name='RondaSecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField()),
                ('punto_control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkpoints.puntocontrol')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rondas.ronda')),
            ],
            options={
                'db_table': 'ronda_secuencia',
                'constraints': [models.UniqueConstraint(fields=('ronda', 'punto_control'), name='uq_ronda_secuencia')],
            },
        ),
    ]
