# Generated by Django 5.2.15 on 2026-06-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronda',
            name='orden_aleatorio',
            field=models.BooleanField(default=True),
        ),
    ]
