# Generated by Django 5.2.15 on 2026-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondas', '0002_ronda_orden_aleatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='repite',
            field=models.CharField(choices=[('todos_los_dias', 'Todos los días'), ('lunes_a_viernes', 'Lunes a Viernes'), ('dias_semana', 'Días de la semana'), ('una_vez_al_mes', 'Una vez al mes')], max_length=20),
        ),
    ]
