# Generated by Django 5.2.15 on 2026-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondas', '0003_alter_programacion_repite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacionhorario',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='programacionhorario',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ronda',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ronda',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
