# Generated by Django 5.2.15 on 2026-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('codigo_cc', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='privado', max_length=255)),
                ('id_licitacion', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_mensual_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('cantidad_admin_contrato', models.IntegerField(default=1)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio_contrato', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_contrato', models.DateTimeField(blank=True, null=True)),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('reajuste_ipc', models.BooleanField(default=False)),
                ('reajuste_imm', models.BooleanField(default=False)),
                ('porcentaje_reajuste_ipc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_variacion_imm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('periodicidad_reajuste', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'indexes': [models.Index(fields=['rut'], name='cliente_rut_09d755_idx')],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('cliente_id', models.BigIntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(default='media', max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('dotacion_requerida', models.IntegerField(default=1)),
                ('cantidad_guardias', models.IntegerField(default=1)),
                ('cantidad_supervisores', models.IntegerField(default=0)),
                ('certificaciones_requeridas', models.JSONField(blank=True, null=True)),
                ('edad_minima_hombres', models.IntegerField(blank=True, null=True)),
                ('edad_maxima_hombres', models.IntegerField(blank=True, null=True)),
                ('edad_minima_mujeres', models.IntegerField(blank=True, null=True)),
                ('edad_maxima_mujeres', models.IntegerField(blank=True, null=True)),
                ('requisito_idioma', models.CharField(blank=True, max_length=255, null=True)),
                ('experiencia_requerida', models.TextField(blank=True, null=True)),
                ('capacitacion_requerida', models.TextField(blank=True, null=True)),
                ('habilidades_especificas', models.TextField(blank=True, null=True)),
                ('permite_ley_inclusion', models.BooleanField(default=False)),
                ('valor_turno_extra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_jornada_ordinaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instalacion',
                'indexes': [models.Index(fields=['cliente_id'], name='instalacion_cliente_c8bd6c_idx')],
            },
        ),
    ]
