# Generated by Django 5.2.15 on 2026-06-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rondas', '0003_alter_programacion_repite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RondaEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardia_keycloak_id', models.CharField(db_index=True, max_length=36)),
                ('instalacion_id', models.BigIntegerField(db_index=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completada', 'Completada')], default='en_curso', max_length=12)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rondas.ronda')),
            ],
            options={
                'db_table': 'ronda_ejecucion',
            },
        ),
    ]
