# Generated by Django 5.2.15 on 2026-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desplazamiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('recinto', models.CharField(max_length=120)),
                ('ppu', models.CharField(max_length=30)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('tipo_vehiculo', models.CharField(choices=[('motocicleta', 'Motocicleta'), ('furgon', 'Furgón'), ('auto', 'Auto'), ('station_wagon', 'Station Wagon'), ('camioneta', 'Camioneta'), ('mini_bus', 'Mini Bus')], max_length=20)),
                ('nombre_conductor', models.CharField(max_length=160)),
                ('codigo_conductor', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(choices=[('primer_turno', '1er turno'), ('segundo_turno', '2do turno'), ('tercer_turno', '3er turno'), ('intermedio', 'Intermedio'), ('turno_largo', 'Turno largo'), ('turno_especial', 'Turno especial')], max_length=20)),
                ('registrado_keycloak_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
    ]
